// Package jwt provides RS256 JWT creation and verification for back-channel logout tokens.
// The OIDC Back-Channel Logout spec (RFC draft) requires a signed "Logout Token"
// containing specific claims (sub, sid, events). RS256 is mandatory over HS256
// so that receiving parties can verify without sharing a symmetric secret.
package jwt

import (
	"crypto/rsa"
	"fmt"
	"time"

	gojwt "github.com/golang-jwt/jwt/v5"
	"github.com/google/uuid"
)

const (
	// LogoutEventClaim is the fixed claim key required by the OIDC Back-Channel Logout spec.
	LogoutEventClaim = "http://schemas.openid.net/event/backchannel-logout"
)

// LogoutTokenClaims represents the JWT payload for a Back-Channel Logout Token.
// Fields follow the OIDC Back-Channel Logout 1.0 specification.
type LogoutTokenClaims struct {
	// Events is a JSON object whose key signals the logout event type.
	Events map[string]interface{} `json:"events"`
	// SessionID is the OIDC sid claim identifying the browser session being terminated.
	SessionID string `json:"sid,omitempty"`
	gojwt.RegisteredClaims
}

// Service signs and verifies RS256 JWTs for logout tokens.
type Service struct {
	privateKey *rsa.PrivateKey
	publicKey  *rsa.PublicKey
	issuer     string
	keyID      string
}

// NewService constructs a JWT Service. The issuer is embedded in every token
// so recipients can validate the iss claim against their expected IdP.
func NewService(privateKey *rsa.PrivateKey, publicKey *rsa.PublicKey, issuer, keyID string) *Service {
	return &Service{
		privateKey: privateKey,
		publicKey:  publicKey,
		issuer:     issuer,
		keyID:      keyID,
	}
}

// MintLogoutToken creates a signed RS256 logout token for a given subject and session.
// The token is intentionally short-lived (2 minutes) because it is delivered immediately
// via HTTP POST to each registered back-channel endpoint.
func (s *Service) MintLogoutToken(subject, sessionID string) (string, error) {
	now := time.Now().UTC()

	claims := LogoutTokenClaims{
		Events: map[string]interface{}{
			LogoutEventClaim: struct{}{},
		},
		SessionID: sessionID,
		RegisteredClaims: gojwt.RegisteredClaims{
			Issuer:    s.issuer,
			Subject:   subject,
			IssuedAt:  gojwt.NewNumericDate(now),
			ExpiresAt: gojwt.NewNumericDate(now.Add(2 * time.Minute)),
			// jti prevents replay attacks by making every logout token unique.
			ID: uuid.New().String(),
		},
	}

	token := gojwt.NewWithClaims(gojwt.SigningMethodRS256, claims)
	// kid allows JWKS-based key rotation: receivers identify the correct public key.
	token.Header["kid"] = s.keyID

	signed, err := token.SignedString(s.privateKey)
	if err != nil {
		return "", fmt.Errorf("sign logout token: %w", err)
	}

	return signed, nil
}

// VerifyLogoutToken parses and validates an RS256 logout token string.
// Returns the decoded claims on success.
func (s *Service) VerifyLogoutToken(tokenString string) (*LogoutTokenClaims, error) {
	claims := &LogoutTokenClaims{}

	token, err := gojwt.ParseWithClaims(tokenString, claims, func(t *gojwt.Token) (interface{}, error) {
		// Reject non-RSA algorithms to prevent algorithm confusion attacks.
		if _, ok := t.Method.(*gojwt.SigningMethodRSA); !ok {
			return nil, fmt.Errorf("unexpected signing method: %v", t.Header["alg"])
		}
		return s.publicKey, nil
	}, gojwt.WithIssuedAt(), gojwt.WithExpirationRequired())

	if err != nil {
		return nil, fmt.Errorf("parse logout token: %w", err)
	}

	if !token.Valid {
		return nil, fmt.Errorf("logout token is invalid")
	}

	// Enforce that the events claim contains the required logout event key.
	if _, ok := claims.Events[LogoutEventClaim]; !ok {
		return nil, fmt.Errorf("logout token missing required events claim")
	}

	return claims, nil
}

// PKCEChallenge holds the PKCE code_verifier / code_challenge pair for mobile OAuth flows.
// The verifier is generated by the client; this struct is used server-side to validate.
type PKCEChallenge struct {
	CodeVerifier  string
	CodeChallenge string
	Method        string // always "S256" — plain is not accepted
}
