#!/usr/bin/env bash
# ============================================================
# generate-secrets.sh
#
# Generates all cryptographic material required by the
# SSO Identity Hub before first deployment.
#
# Run this ONCE on the VPS before starting docker-compose.
# Output is placed in ./secrets/ which is .gitignore'd.
#
# Dependencies: openssl (pre-installed on any modern Linux)
# ============================================================
set -euo pipefail

SECRETS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/secrets"

echo "[*] Creating secrets directory: ${SECRETS_DIR}"
mkdir -p "${SECRETS_DIR}"
chmod 700 "${SECRETS_DIR}"

# ---- 1. RSA-4096 key pair for RS256 logout token signing ---
echo "[*] Generating RSA-4096 private key (PKCS#8, no passphrase)..."
openssl genpkey \
    -algorithm RSA \
    -pkeyopt rsa_keygen_bits:4096 \
    -out "${SECRETS_DIR}/rsa_private.pem"

echo "[*] Deriving RSA public key..."
openssl rsa \
    -pubout \
    -in  "${SECRETS_DIR}/rsa_private.pem" \
    -out "${SECRETS_DIR}/rsa_public.pem"

chmod 600 "${SECRETS_DIR}/rsa_private.pem"
chmod 644 "${SECRETS_DIR}/rsa_public.pem"

# ---- 2. Strong random secrets for DB and SCIM bearer token -
echo "[*] Generating random secret values..."

POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -d '=+/' | head -c 40)
SCIM_BEARER_TOKEN=$(openssl rand -base64 48 | tr -d '=+/' | head -c 64)

SECRETS_ENV="${SECRETS_DIR}/generated.env"
cat > "${SECRETS_ENV}" <<EOF
# Auto-generated by generate-secrets.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Copy these values into your production .env file.
# DELETE this file after copying.
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
SCIM_BEARER_TOKEN=${SCIM_BEARER_TOKEN}
EOF
chmod 600 "${SECRETS_ENV}"

# ---- 3. Extract the RSA public key as a base64 DER for JWKS -
echo "[*] Exporting DER public key for JWKS embedding..."
openssl rsa \
    -pubin \
    -in  "${SECRETS_DIR}/rsa_public.pem" \
    -outform DER \
    -out "${SECRETS_DIR}/rsa_public.der" 2>/dev/null
chmod 644 "${SECRETS_DIR}/rsa_public.der"

echo ""
echo "================================================================"
echo " Secrets generated successfully."
echo ""
echo " Files created:"
echo "   ${SECRETS_DIR}/rsa_private.pem   <- JWT signing key (KEEP SECRET)"
echo "   ${SECRETS_DIR}/rsa_public.pem    <- JWT verification key"
echo "   ${SECRETS_DIR}/rsa_public.der    <- DER for JWKS endpoint"
echo "   ${SECRETS_DIR}/generated.env     <- DB + SCIM passwords (copy to .env)"
echo ""
echo " NEXT STEPS:"
echo "   1. cat ${SECRETS_DIR}/generated.env"
echo "   2. Copy POSTGRES_PASSWORD and SCIM_BEARER_TOKEN into .env"
echo "   3. rm ${SECRETS_DIR}/generated.env"
echo "   4. Set JWT_RS256_PRIVATE_KEY_PATH=/secrets/rsa_private.pem in .env"
echo "   5. Set JWT_RS256_PUBLIC_KEY_PATH=/secrets/rsa_public.pem in .env"
echo "================================================================"
